<?php

return [
    'enabled' => env('WEBHOOK_NOTIFICATIONS_ENABLED', false),
    'connection' => env('WEBHOOK_QUEUE_CONNECTION', 'database'),
    'queue' => env('WEBHOOK_QUEUE_NAME', 'webhooks'),
    'connect_timeout' => (int) env('WEBHOOK_CONNECT_TIMEOUT', 5),
    'timeout' => (int) env('WEBHOOK_TIMEOUT', 15),
    'processing_timeout' => (int) env('WEBHOOK_PROCESSING_TIMEOUT', 60),
    'max_attempts' => (int) env('WEBHOOK_MAX_ATTEMPTS', 8),
    'retry_delays' => [60, 300, 900, 3600, 10800, 21600, 43200],
    'default_rate_limit' => (int) env('WEBHOOK_RATE_LIMIT_PER_MINUTE', 25),
    'maximum_rate_limit' => 30,
    'max_rejected_attempts' => (int) env('DOMICILIATION_MAX_REJECTED_ATTEMPTS', 3),
    'cancellation_retry_seconds' => (int) env('DOMICILIATION_CANCELLATION_RETRY_SECONDS', 300),
    'events' => [
        'payment_link.payment.approved' => ['label' => 'Pago aprobado de liga unica', 'group' => 'Liga de Pago Unica'],
        'payment_link.payment.rejected' => ['label' => 'Pago rechazado de liga unica', 'group' => 'Liga de Pago Unica'],
        'domiciliation_link.payment.approved' => ['label' => 'Pago aprobado de liga de domiciliacion', 'group' => 'Domiciliacion'],
        'domiciliation_link.payment.rejected' => ['label' => 'Pago rechazado de liga de domiciliacion', 'group' => 'Domiciliacion'],
        'domiciliation.activated' => ['label' => 'Domiciliacion activada', 'group' => 'Domiciliacion'],
        'domiciliation.activation_failed' => ['label' => 'Fallo de activacion de domiciliacion', 'group' => 'Domiciliacion'],
        'domiciliation.cancelled' => ['label' => 'Domiciliacion cancelada', 'group' => 'Domiciliacion'],
        'domiciliation.cancellation_failed' => ['label' => 'Fallo al cancelar domiciliacion', 'group' => 'Domiciliacion'],
        'recurring_charge.approved' => ['label' => 'Cargo recurrente aprobado', 'group' => 'Cargos Recurrentes', 'sources' => ['all', 'manual', 'api', 'automatic']],
        'recurring_charge.rejected' => ['label' => 'Cargo recurrente rechazado', 'group' => 'Cargos Recurrentes', 'sources' => ['all', 'manual', 'api', 'automatic']],
        'recurring_charge.error' => ['label' => 'Error de cargo recurrente', 'group' => 'Cargos Recurrentes', 'sources' => ['all', 'manual', 'api', 'automatic']],
        'spei.payment.approved' => ['label' => 'Pago SPEI aprobado', 'group' => 'SPEI'],
        'spei.payment.rejected' => ['label' => 'Pago SPEI rechazado', 'group' => 'SPEI'],
        'spei.payment.cancelled' => ['label' => 'Pago SPEI cancelado', 'group' => 'SPEI'],
        'spei.payment.cancellation_rejected' => ['label' => 'Cancelacion SPEI rechazada', 'group' => 'SPEI'],
        'terminal.payment.approved' => ['label' => 'Pago de terminal aprobado', 'group' => 'Terminal'],
        'terminal.payment.rejected' => ['label' => 'Pago de terminal rechazado', 'group' => 'Terminal'],
        'terminal.cancelled' => ['label' => 'Liga de terminal cancelada', 'group' => 'Terminal'],
        'terminal.cancellation_failed' => ['label' => 'Fallo al cancelar terminal', 'group' => 'Terminal'],
        'webhook.endpoint.test' => ['label' => 'Prueba de endpoint', 'group' => 'Sistema'],
    ],
];
